- hosts: myhosts
  gather_facts: false
  tasks:
    - block:
        - command: "head -1 /etc/motd"
          register: result
      rescue:
        - meta: clear_host_errors

    - set_fact:
        result_dict: "{{ result.failed|
                         ternary('cause: connection timed out',
                                 result.stdout) }}"
    - debug:
        var: result_dict

# Ansible set fact for a failure
# https://stackoverflow.com/questions/59328387/ansible-set-fact-for-a-failure/

# It's possible to use Blocks error handling "to handle errors in a way
# similar to exceptions in most programming languages". For example
# 
# gives
# 
# ok: [test_01] => {
#     "result_dict": "FreeBSD 12.0-RELEASE r341666 GENERIC "
# }
# ok: [test_02] => {
#     "result_dict": "FreeBSD 12.0-RELEASE r341666 GENERIC "
# }
# ok: [test_03] => {
#     "result_dict": "FreeBSD 12.0-RELEASE r341666 GENERIC "
# }
# ok: [test_04] => {
#     "result_dict": "cause: connection timed out"
# }
